name: offline_form
description: A Project to Explore Firestore Offline Mode.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.9.2
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
